version: '2'
services:
  webserver:
    image: openjdk:8
    ports:
      - 8000:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - tremoteLaboratory
    command: ["java","-Xmx128M","-Djava.security.egd=file:/dev/./urandom","-jar","/app/tremoteLaboratory.jar"]

  tremoteLaboratory:
    image: public/tremoteLaboratory:1.0-SNAPSHOT
    volumes:
      - /app

