version: '2'
services:

  mysql:
    image: mysql:5.7.17
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=LABORATORY
      - MYSQL_USER=laboratory
      - MYSQL_PASSWORD=laboratory
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-buffer-pool-size=5368709120 --innodb_buffer_pool_chunk_size=671088640 --max_allowed_packet=1073741824
#    networks:
#      app_net:
#        ipv4_address: 10.10.10.1

  redis:
    image: redis:3-alpine

    ports:
      - 6379:6379
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${REDIS_DATA}:/data

    command: redis-server --appendonly yes
#    networks:
#      app_net:
#        ipv4_address: 10.10.10.2
    depends_on:
      - mysql
  webserver:
    image: public/java
    ports:
      - 8000:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${WEB_DIST_PATH}:/static
      - ${LOG_DIR}:/log
    volumes_from:
      - remoteLaboratory
    command: ["/wait-for.sh","redis:6379","-t","120","--","java","-Xmx128M","-Djava.security.egd=file:/dev/./urandom","-Dlogging.file=/log/app.log","-Dlogging.level=debug","-jar","/app/remoteLaboratory.jar"]
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - redis
#    networks:
#      app_net:
#        ipv4_address: 10.10.10.3
  remoteLaboratory:
    image: public/remote_laboratory:1.0-SNAPSHOT
    volumes:
      - /app


  srs:
    image: registry.linkme8.cn:5000/turbo/srs:2.0-r5-ffmpeg41-dev
    ports:
      - 1935
      - 1985
      - 443
      - 8001:80
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

      - /dev/shm:/host_shm
    environment:
      - SRS_ID=srs1
      - SERVICE_URL=http://localhost:8000/remoteLaboratory
      - AUTH_CAM=false
      - SERVICE_API_VERSION=v1
      - USE_DVR=false


    logging:
      options:
        max-size: "10m"
        max-file: "10"