version: '2'
services:
  mysql:
    image: mysql:5.7.17
    ports:
      - 3306:3306
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=LABORATORY
      - MYSQL_USER=laboratory
      - MYSQL_PASSWORD=laboratory
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-buffer-pool-size=5368709120 --innodb_buffer_pool_chunk_size=671088640 --max_allowed_packet=1073741824
    networks:
      app_net:
        ipv4_address: 10.10.10.1
  redis:
    image: redis:5-alpine

    ports:
      - 6379:6379
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${REDIS_DATA}:/data

    command: redis-server --appendonly yes
    networks:
      app_net:
        ipv4_address: 10.10.10.2

  webserver:
    image: public/java
    ports:
      - 8000:8000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${UPLOAD_DATA}:/temp
      - ${LOG_DIR}:/log
    volumes_from:
      - tremoteLaboratory
    command: ["/wait-for.sh","mysql:3306","-t","60","--","java","-Xmx128M","-Djava.security.egd=file:/dev/./urandom","-Dlogging.file=/log/app.log","-jar","/app/tremoteLaboratory.jar"]
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
    networks:
      app_net:
        ipv4_address: 10.10.10.3
  tremoteLaboratory:
    image: public/tremote_laboratory:1.0-SNAPSHOT
    volumes:
      - /app

networks:
# 配置docker network
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
                # 子网络
      - subnet: 10.10.0.0/16
